# Generated by Django 3.2.4 on 2021-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allconfessions',
            name='confesson',
        ),
        migrations.AddField(
            model_name='allconfessions',
            name='confession',
            field=models.TextField(max_length=240, null=True),
        ),
    ]
